### ISSUE TITLE
Fails to build on the pkg-build server because of symbolic link

### ISSUE THREAD

**Issue by samth** [bluephoenix47/pgmp#10]
The symbolic link in "scheme/perflinty/utils.ss" causes the Racket pkg-build service to fail on this package: http://pkg-build.racket-lang.org/server/built/fail/rackpgmp.txt

**Comment by wilbowma** [comment]
@samth Didn't this happen before, in #9?

**Comment by samth** [comment]
Yeah, but I was confused in #9, plus at that time Racket was ok with symlinks in other parts of the repo (which it no longer is).

**Comment by wilbowma** [comment]
@samth That file isn't part of the package; why should raco try to touch it?

**Comment by samth** [comment]
The thing that fails is the catalog archiver (which is part of how the pkg-build system works). When unpacking the archive (before it even gets to looking at the code), it sees an upward symlink and gets worried. @mflatt can say more.

**Comment by wilbowma** [comment]
Hm. Well, that symlink _is_ a hack, but it's also just reference code. I'll see what I can do.

**Comment by samth** [comment]
Thanks!
